### ISSUE TITLE
Не получается отменить платеж до оплаты

### ISSUE THREAD

**Issue by aawee0** [assist-group/assist-mcommerce-sdk-android#10]
Доброго времени суток,

Использую SDK версии 1.4.2. Оплата проходит без проблем, за исключением одного случая: если пользователь не завершает платеж или отменяет его.
При подобной отмене пробую вызывать метод void stopPayment(Activity caller) класса AssistBasePayEngine. Однако при повторной попытке оплаты, получаю ошибку:

"Платеж с таким номером находится в обработке.
Payment with that number is being processed."

Вопрос в следующем: достаточно ли вызова stopPayment для отмены платежа и если нет, какова последовательность действий при отмене платежа до перевода средств? 

Прикладываю часть логов: данные двух попыток платежа и ответ сервера. При необходимости, могу выложить любую другую информацию.

С уважением,
Евгений

[assist_log_problem.txt](https://github.com/assist-group/assist-mcommerce-sdk-android/files/958883/assist_log_problem.txt)

**Comment by serg-assist** [comment]
stopPayment не отменяет, а просто прерывает платеж. Т.е. платеж может уйти или мог не уйти в Assist. Если он прервался уже в процессе проведения, например при вводе данных, то какое-то время такой заказ будет висеть в системе и через некторое время автоматически закроется неуспешно. Если прервать в конце на момент получения результата, то скорее всего такой платеж будет оплачен и можно будет узнать его статус с помощью getOrderResult

**Comment by aawee0** [comment]
Благодарю за ответ! Судя по всему платеж уже ушел в Assist, потом как возвращается ответ при повторной попытке оплаты - "Платеж с таким номером находится в обработке."

Хотел узнать, как лучше действовать в случае выхода пользователем из процесса оплаты. 
Есть ли методы, осуществляющие отмену платежа, или в этом случае лучше создавать новый платеж с другим номером?

**Comment by serg-assist** [comment]
по незавершенному платежу можно узнать статус и если он в процессе то лучше использовать другой номер. у ассиста есть сервис отмены, но он для оплаченных платежей, в sdk не сделан его вызов, т.к. там требуется логин/пароль мерчанта, решили что это может быть небезопасно хранить в приложении

**Comment by aawee0** [comment]
Спасибо! Насчёт номера тоже хотел спросить, какой номер является ID для платежа, т.е. является уникальным? Является ли им OrderNumber из класса AssistPaymentData?

**Comment by serg-assist** [comment]
номер OrderNumber является уникальным когда он в процессе, это защита от двойных списаний, также вы можете задать его уникальным в настройках мерчанта в личном кабинете Ассист, тогда он будет всегда уникальным. В результате платежа возвращается BillNumber он уникальный в системе Ассист для всех платежей

**Comment by aawee0** [comment]
Дело в том, что в приложении на данный момент в качестве OrderNumber используется номер заказа в системе, несвязанной с Assist. 

Но очевидно из-за случая, изложенного выше (пользователь отменяет оплату, но потом решает заплатить еще раз с теми же данными), лучше использовать в качестве OrderNumber некий отдельный номер, который можно менять при повторном заведении платежа. 

Но тогда вопрос, как этот номер выбирать. Есть ли в SDK методы, позволяющие узнать, к примеру, любой доступный номер, т.е. не присвоенный никакому активному платежу?

**Comment by serg-assist** [comment]
в данном случае уникальность номера проверяется для merchant_id, а не глобально на всю систему, т.е. вы сами можете контролировать уникальность по вашему merchant_id
