### ISSUE TITLE
Интеграция Apple Pay с Assist. Не работает "Оплата через ApplePay"

### ISSUE THREAD

**Issue by pawga** [assist-group/assist-mcommerce-sdk-android#14]
Есть задача по интеграции Apple Pay в связке с Assist

В тестовом приложении AssistMobileTest проверили два режима работы. Результат такой: "просто" оплатить  **"success: bill=5928654230583157, state=Approved, message=Optional(" ")"**
Но при оплате через ApplePay **"Finished: bill = , status = Unknown, message - firstcode: 2, secondcode: Optional(0)** . Т е тестовая оплата не прошла. 

Вопрос: что нужно сделать для интеграции Apple Pay с Assist? В документации Apple есть такая фраза "Obtain a CSR file from your Payment Provider.
Contact your payment provider to obtain a properly formatted CSR for you to upload and create your certificate."  Т е нам нужно у вас получить CSR для создания полноценного сертификата для взаимодействия с Assist. Так? Напишите правильную последовательность по настройке Apple Pay с вашим сервисом для iOS.

**Comment by serg-assist** [comment]
Нужно сгенерить его в ЛК Ассист как описано в инструкции 
https://www.assist.ru/files/AccountNEW.pdf
см. раздел 8.2.9

**Comment by pawga** [comment]
Спасибо.
