### ISSUE TITLE
Why AssistPaymentData hasn't BillNumber?

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#15]
In version 1.4.2 :
```
public class AssistPaymentData{
...
 public void setBillNumber(String value) {
        values.put(FieldName.BillNumber, value);
    }
...
```
In version 1.5.0 :
```
public class AssistPaymentData{
...
public void setPaymentToken(String value) {
        values.put(FieldName.PaymentToken, value.toString());
    }
...
```

But In version 1.4.2  and in 1.5.0 `AssistResult.class` has  `billNumber`:
```
public class AssistResult {
 ...
    private String billNumber;
...
```
Does `BillNumber` is renamed to `PaymentToken`? And it's not renamed in `AssistResult.class`?

**Comment by serg-assist** [comment]
Because billNumber is identifier of payment in Assist system, so it's generated when payment run through Assist and returned in result. It may be used for cancel of payments.

**Comment by Kolyall** [comment]
@serg-assist Так получается чтобы сделать рекурентный платеж нужно поле `PaymentToken` вместо `BillNumber` со значением  `billNumber` ?

**Comment by Kolyall** [comment]
И вообще раньше:
 было `Currency` теперь `OrderCurrency`? 
было `Amount` теперь `OrderAmount`?

**Comment by serg-assist** [comment]
рекуррентный платеж это отдельный сервис, который в sdk не поддерживается, что у вас была заверсия? возможно кто-то ее доработал специально под вас? в гите такой версии точно не было

**Comment by Kolyall** [comment]
@serg-assist я сам дорабатывал, постоянно общаясь с assist по почте, просто не понял почему некоторые поля были удалены, думал их просто переименовали в новой версии 1.5.0, поэтому и спрашивал
