### ISSUE TITLE
Почему сайт 3D Secure не на весь экран?

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#22]
Почему сайт 3D Secure столь маленький (не на весь экран)? Это сайт у банка не адаптирован или в WebView не добавлены параметры?

![screenshot131](https://user-images.githubusercontent.com/3495165/41350338-846de752-6f1b-11e8-90e0-dfdbcbbfa54d.png)

**Comment by Kolyall** [comment]
поставил в `ru.assisttech.sdk.processor.WebViewActivity.class`:
вместо:
` wv.getSettings().setUseWideViewPort(true);`
вот это:
 ` wv.getSettings().setUseWideViewPort(false);`

Стало отображаться более презентабельно, так:
![screenshot132](https://user-images.githubusercontent.com/3495165/41352235-8fa9345e-6f21-11e8-9469-505fa640ce76.png)

**Comment by serg-assist** [comment]
ok, добавил
