### ISSUE TITLE
Почему тестовый сайт не презентабельный?

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#24]
Почему тестовый сайт не такой презентабельный, как реальный?

Тестовый https://test.paysec.by/pay/order.cfm

![screenshot133](https://user-images.githubusercontent.com/3495165/41353214-419be10a-6f24-11e8-8734-f924247cc524.png)

Реальный:

![screenshot126](https://user-images.githubusercontent.com/3495165/41353168-1970b1d8-6f24-11e8-97e5-7afdc7a9d19c.png)

**Comment by serg-assist** [comment]
это вам нужно в сапорт Ассиста обратиться чтобы они включили шаблоны мобильных страниц на тестовой зоне как на боевой, я скажу им со своей стороны =)

**Comment by serg-assist** [comment]
напишите на support@belassist.by  и укажите свой merchant_id
