### ISSUE TITLE
Не закрывается экран отплаты WebViewActivity после успешной/не успешной оплаты

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#27]
в версии 1.4.2 он закрывался , а в 1.5.0 остается открытым, т.е. callback в PayEngineListener приходит, но WebViewActivity остается открытой:

See [Log File.txt](https://www.dropbox.com/s/lhamg18w02go8hi/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B9%20%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82.txt?dl=1)

![screenshot127](https://user-images.githubusercontent.com/3495165/41399271-87b9fe8a-6fc2-11e8-867d-eace9804a212.png)

**Comment by serg-assist** [comment]
добавил закрытие Activity
