### ISSUE TITLE
Поля равняются null в PayEngineListener.onFinished у  AssistResult  в `assistTransaction.getResult()`

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#28]
https://github.com/assist-group/assist-mcommerce-sdk-android/blob/5c5e3b6a4c5006c5a79aaaf1066207bc5c41a060/sdk/src/main/java/ru/assisttech/sdk/AssistResult.java#L28

При успешной оплате в метод  `ru.assisttech.sdk.engine.PayEngineListener#onFinished` приходит  объект  ` ru.assisttech.sdk.storage.AssistTransaction` 

Если у него взять  ` AssistResult result = assistTransaction.getResult();`
То у `result.getMeanNumber()` будет равным `null`

**Comment by serg-assist** [comment]
добавил поля в базу
