### ISSUE TITLE
Замените строки на поля из ru.assisttech.sdk.FieldName

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#30]
https://github.com/assist-group/assist-mcommerce-sdk-android/blob/7057851d59c02c8b67194821d2886face9913fce/sdk/src/main/java/ru/assisttech/sdk/processor/AssistSilentpayProcessor.java#L67

Замените строки на поля из ru.assisttech.sdk.FieldName

**Comment by serg-assist** [comment]
добавил, но не все т.к. в FieldName поля для сервиса order.cfm, в silentpay некоторые названия отличаются
