### ISSUE TITLE
Почему переименовали Build.MODEL в "CommerceSDK"

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#32]
https://github.com/assist-group/assist-mcommerce-sdk-android/blob/5c5e3b6a4c5006c5a79aaaf1066207bc5c41a060/sdk/src/main/java/ru/assisttech/sdk/processor/AssistWebProcessor.java#L184

Почему переименовали Build.MODEL в "CommerceSDK"? Это обязательное поле при рекурентном платеже?

**Comment by serg-assist** [comment]
это индикация того что платеж выполнен через SDK, чтобы понимать откуда он, если что-то пошло не так
