### ISSUE TITLE
Падение приложения: Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by mikekudzin** [assist-group/assist-mcommerce-sdk-android#43]
Ошибка: 
Приложение падает при совершении платежа.

Stack trace из крашлитика:
`Fatal Exception: java.lang.IllegalArgumentException
View=DecorView@94d175b[] not attached to window manager
android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:513)
android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:422)
android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:126)
android.app.Dialog.dismissDialog (Dialog.java:370)
android.app.Dialog.dismiss (Dialog.java:353)
ru.assisttech.sdk.engine.AssistPayEngine.closeProgressDialog (AssistPayEngine.java:482)
ru.assisttech.sdk.engine.AssistPayEngine.access$600 (AssistPayEngine.java:42)
ru.assisttech.sdk.engine.AssistPayEngine$ConnectionCheckListener.onConnectionSuccess (AssistPayEngine.java:499)
ru.assisttech.sdk.network.AssistNetworkEngine$CheckHTTPSConnectionTask.onPostExecute (AssistNetworkEngine.java:236)
ru.assisttech.sdk.network.AssistNetworkEngine$CheckHTTPSConnectionTask.onPostExecute (AssistNetworkEngine.java:128)
android.os.AsyncTask.finish (AsyncTask.java:667)
android.os.AsyncTask.-wrap1 (AsyncTask.java)
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:684)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:163)`

Дополнительное описание:
This is a crash caused by your app dismissing a dialog attached to an Activity which is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated.
http://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash

**Comment by serg-assist** [comment]
на какой стадии оплаты происходит такое падение?

**Comment by mikekudzin** [comment]
@serg-assist Конкретных шагов воспроизведения нет. Это падения у пользователей в проде.

**Comment by serg-assist** [comment]
залил исправление
