### ISSUE TITLE
Порядок подключение к Assist клиента Android

### ISSUE THREAD

**Issue by pawga** [assist-group/assist-mcommerce-sdk-android#8]
Здравствуйте! До недавнего времени мы работали с другой платежной системой, сейчас планируется подключения еще и к Assist.  С первой платежной системой мы работали через Webview и все было нормально. Сейчас наши сервисы нам уже шлют тестовые url для работы с Assist . Первая попытка "легко" подключиться не увенчалась успехом . Webview отображает пустой экран (при просмотре страницы которую он содержит - пустые body блок и head), в логах по этой теме единственное сообщение **W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: xxxx** .  При просмотре через браузер содержимое от Assist отображается.  Что не так с работой через Webview?   И какая правильная последовательность подключения мобильного клиента (Android ) к Assist?

**Comment by serg-assist** [comment]
Добрый день, наш SDK также использует webview для отображения платежных страниц, можете его использовать как пример, исходники здесь выложены. Судя по вашей ошибке какая-то проблема с коннектом у процесса, возможно проблема с сертификатом, т.к. на тестовой зоне он самоподписаный и его нужно заранее подгрузить, вы какой-то фреймворк используете?

**Comment by pawga** [comment]
Добрый день! Разобрались. Webview требует для работы с Assist  более тонкой настройки. Ваш пример тоже помог в решении данной проблемы. Спасибо.
