### ISSUE TITLE
Как использовать  реквизиты сохраненной карты при совершении покупки с помощью  Webview?

### ISSUE THREAD

**Issue by pawga** [assist-group/assist-mcommerce-sdk-android#9]
Здравствуйте! 

Как использовать данные  сохраненной карты при оплате покупки, используя контрол Webview?   У вас в эталонном примере есть функциональность для сохранения реквизитов карты, но как эти данные по карте задействовать при оформлении покупки через webview, мы не нашли.

**Comment by serg-assist** [comment]
Добрый день!

Вы имеете ввиду OneClick, когда карта сохраняется у нас в системе
должна быть включена поддержка OneClick у магазина
вот описание https://www.assist.ru/files/OneClick.pdf
при инициации оплаты нужно передать параметр CustomerNumber, а в WebView должно работать по нужному сценарию автоматически
